[package]
name = "FinSc-Hadron-Wiki"
version = "0.1.0"
ipkg = "FinSc-Hadron-Wiki.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"

[custom.all.FinSc-Physics]
type = "local"
path = "../FinSc-Physics"
ipkg = "FinSc-Physics.ipkg"

[custom.all.FinSc-Hadron]
type = "local"
path = "../FinSc-Hadron"
ipkg = "FinSc-Hadron.ipkg"
